matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx

language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; sudo apt-get install -y libqt4-dev libqwt5-qt4-dev libfftw3-dev libglu1-mesa-dev libasound2-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew tap cartr/qt4; brew tap-pin cartr/qt4; brew install -v glfw fftw qwt-qt4 ; find /usr/local -name qwt.h ; echo $QWT_ROOT; fi
# QT 5  / QWT 6 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install qt glfw qwt; fi
script:
  - ls /usr/local/Cellar/qwt-qt4/
  - ls /usr/local/Cellar/qwt-qt4/6.1.3_1/
  - ls /usr/local/Cellar/qwt-qt4/6.1.3_1/lib
  - ls /usr/local/Cellar/qwt-qt4/6.1.3_1/lib/qwt.framework
  - ls /usr/local/Cellar/qwt-qt4/6.1.3_1/lib/qwt.framework/Versions
  - ls /usr/local/Cellar/qwt-qt4/6.1.3_1/lib/qwt.framework/Versions/6
  - ls /usr/local/Cellar/qwt-qt4/6.1.3_1/lib/qwt.framework/Versions/6/Headers
  - qmake pitch.pro
  - make
  - mkdir cmake-build; cd cmake-build
  - cmake ..
  - make
#EOF
