matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx

language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; sudo apt-get install -y libqt4-dev libqwt5-qt4-dev libfftw3-dev libglu1-mesa-dev libasound2-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew tap cartr/qt4; brew tap-pin cartr/qt4; brew install -v qwt-qt4 ; find /usr/include -name qwt.h ; fi
# QT 5  / QWT 6 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install qt glfw qwt; fi
script:
  - qmake pitch.pro
  - make
  - mkdir cmake-build; cd cmake-build
  - cmake ..
  - make
#EOF
